## Quiz #0102 

#### Use a lambda function and map() to answer the following questions.

1). Add 1 to each element of the list 'a' and create another list. <br>

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
a=[1,2,3,4,5,6,7,8,9,10]
print('a =',list(map(lambda x:x+1, a)))

a = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


2). Multiply element-wise the lists 'a' and 'b'. Show the result as another list.

a = [2, 4, 6, 8, 10]

b = [10, 8, 6, 4, 2]

In [5]:
import numpy as np

a = np.array([2, 4, 6, 8, 10])
b = np.array([10, 8, 6, 4, 2])
ab_mult=a*b

print('The multiply of a and b is:', ab_mult)

The multiply of a and b is: [20 32 36 32 20]


#### Use a lambda function and filter() to answer the following questions.

3). Find the multiples of 5 in the range 1~100. Show the result as a list.

In [39]:
diveded = [1]+list(filter(lambda x:True if x % 5 == 0 else False, range(101)))
print(diveded)

[1, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]


4). In the following list, find the values larger than 160. Show the result as a list.

a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]

In [65]:
a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]

value=[]
for i in a:
  if i > 160:
    value = value +[i]
print('The values larger than 160 are :', value)

The values larger than 160 are : [160.3, 171.6, 165.34, 167.2, 161.1, 164.9]


5). In the following list, find the values larger than 160 and smaller than 165. Show the result as a list.

a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]

In [67]:
a = [145.2, 160.3, 155.2, 171.6, 165.34, 167.2, 161.1, 164.9]

value=[]
for i in a:
  if i > 160 and i < 165:
    value = value +[i]
print('The values larger than 160 are :', value)

The values larger than 160 are : [160.3, 161.1, 164.9]


6). In the following list of names, extract only those stargin with 'J'. Show the result as a list.

a = ['Sara', 'Jack', 'Rebecca', 'Jennifer', 'Paul', 'Andrew', 'John']

In [44]:
a = ['Sara', 'Jack', 'Rebecca', 'Jennifer', 'Paul', 'Andrew', 'John']
check = 'J'

res = [idx for idx in a if idx[0].lower() == check.lower()]
  
# print result
print("The list of matching first letter : " + str(res))

The list of matching first letter : ['Jack', 'Jennifer', 'John']
